version: "3.9"
services:
  postgres:
    image: postgres:15
    restart: always
    volumes:
      - ./sql/create-db.sql:/docker-entrypoint-initdb.d/create-db.sql
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "8765:8765"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432